M48
; DRILL file {KiCad 7.0.7} date Sun Jul  7 09:27:13 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-07T09:27:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4545Y-3.2244
X4.6455Y-3.2244
T2
X4.4427Y-3.1051
X4.6573Y-3.1051
T0
M30
